version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: cats_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    container_name: cats_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # или любой другой порт, который использует ваше приложение
    container_name: cats_container
    depends_on:
      - redis
      - db
    env_file:     # файл не выгружается на git, добавить руками по примеру .env-exemple
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    restart: on-failure

volumes:
  redis_data:
  db_data: